- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Ensure python is available
      raw: test -e /usr/bin/python || apt install -y --allow-unauthenticated python-minimal

    - name: Ensure python-apt is available
      raw: test -d /usr/share/python-apt || apt install -y --allow-unauthenticated python-apt

    - name: Add gitlab deb source
      raw: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade

- src: https://github.com/geerlingguy/ansible-role-gitlab 
  version: master
  name: geerlingguy.gitlab

- hosts: gl
  remote_user: root
  vars_files:
          - vars/main.yml
  roles:
          - { role: geerlingguy.gitlab }
