- hosts: all
  gather_facts: false
  remote_user: root
  tasks: 

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Ensure python is available
      raw: test -e /usr/bin/python || apt install -y --allow-unauthenticated python-minimal

    - name: Ensure python-apt is available
      raw: test -d /usr/share/python-apt || apt install -y --allow-unauthenticated python-apt

    - name: Add gitlab deb source
      raw: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade

- hosts: gl
  remote_user: root
  vars:
      gitlab_redirect_http_to_https: "false"
      gitlab_external_url: "http://{{ domain_name }}/"
      gitlab_email_enabled: "true"
      gitlab_email_from: "{{ smtp_user }}"
      gitlab_email_reply_to: "{{ smtp_user }}"
      gitlab_email_display_name: "Gitlab"
      gitlab_smtp_enable: "true"
      gitlab_smtp_domain: "{{ smtp_domain_name }}"
      gitlab_smtp_address: "{{ smtp_server }}"
      gitlab_smtp_port: "{{ smtp_port }}"
      gitlab_smtp_user_name: "{{ smtp_user }}"
      gitlab_smtp_password: "{{ smtp_password }}"
      gitlab_smtp_authentication: "login"
      gitlab_smtp_enable_starttls_auto: "true"
      gitlab_smtp_ca_path: "/etc/ssl/certs"
      gitlab_smtp_ca_file: "/etc/ssl/certs/ca-certificates.crt"
  roles:
          - { role: geerlingguy.gitlab }
